// Auto-generated by svelte-realtime — do not edit
// Provides client-side types for $live/ imports

declare module '$live/chat' {
  import type { Readable } from 'svelte/store';
  import type { RpcError } from 'svelte-realtime/client';

  export const sendMessage: (...args: any[]) => Promise<any>;
  export const muteMember: (...args: any[]) => Promise<any>;
  export const unmuteMember: (...args: any[]) => Promise<any>;
  export type ErrorCode = 'FORBIDDEN' | 'NOT_FOUND' | 'UNAUTHORIZED' | 'VALIDATION';
  export const chatAll: (...args: any[]) => Readable<any>;
  export const chatTeamA: (...args: any[]) => Readable<any>;
  export const chatTeamB: (...args: any[]) => Readable<any>;
  export const chatSpectators: (...args: any[]) => Readable<any>;
}

declare module '$live/draft' {
  import type { RpcError } from 'svelte-realtime/client';

  export const pickBan: (...args: any[]) => Promise<any>;
  export type ErrorCode = 'FORBIDDEN' | 'NOT_FOUND' | 'UNAUTHORIZED' | 'VALIDATION';
}

declare module '$live/room' {
  import type { Readable } from 'svelte/store';
  import type { RpcError } from 'svelte-realtime/client';

  export const joinTeam: (...args: any[]) => Promise<any>;
  export const kickMember: (...args: any[]) => Promise<any>;
  export const movePlayer: (...args: any[]) => Promise<any>;
  export const startDraft: (...args: any[]) => Promise<any>;
  export const cancelRoom: (...args: any[]) => Promise<any>;
  export type ErrorCode = 'FORBIDDEN' | 'NOT_FOUND' | 'UNAUTHORIZED' | 'VALIDATION';
  export const lobby: (...args: any[]) => Readable<any>;
}
